services:
  backend:
    build:
      context: .
    restart: always
    ports:
      - "127.0.0.1:8088:8088"
    command: >
      sh -c "
             uvicorn app.main:app --host 0.0.0.0 --port 8088 --reload"
   
  postgres:
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
