services:
  backend:
    build: .
    container_name: backend
    env_file: .env
    depends_on:
      - postgres
    networks:
      - app-network

  # База данных 
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
