services:
  backend:
    build:
      context: .
    ports:
      - "8088:8088"
    volumes:
      - ./app:/app/app
    environment:
      - APPLICATION_DEBUG=True
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8088 --reload"
    stdin_open: true
    tty: true

  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
