services:
  backend:
    build:
      context: .
    restart: always
    ports:
      - "127.0.0.1:8088:8088"
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8088 --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/v1/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
   
  postgres:
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
