"""Add banned_words to rooms

Revision ID: 4225154f3419
Revises: eaeaec86f99d
Create Date: 2025-10-26 03:32:15.835154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4225154f3419'
down_revision: Union[str, Sequence[str], None] = 'eaeaec86f99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room_messages', 'text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=115),
               existing_comment='Текст сообщения',
               existing_nullable=False)
    op.alter_column('room_messages', 'original_text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=115),
               existing_comment='Оригинальный текст (до фильтрации)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room_messages', 'original_text',
               existing_type=sa.String(length=115),
               type_=sa.TEXT(),
               existing_comment='Оригинальный текст (до фильтрации)',
               existing_nullable=False)
    op.alter_column('room_messages', 'text',
               existing_type=sa.String(length=115),
               type_=sa.TEXT(),
               existing_comment='Текст сообщения',
               existing_nullable=False)
    # ### end Alembic commands ###
