"""init tables

Revision ID: 4b5ccaa95386
Revises: 
Create Date: 2025-10-25 01:05:54.226042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b5ccaa95386'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('meets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False, comment='Уникальный код комнаты'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Айди пользователя кто создал встречу'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Является ли встреча активной'),
    sa.Column('schedule', sa.TIMESTAMP(timezone=True), nullable=True, comment='На какую дату запланирована встреча'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда встреча была создана'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meet_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_nickname', sa.String(length=255), nullable=False, comment='Имя пользователя'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='Уникальный токен пользователя'),
    sa.Column('meet_id', sa.Integer(), nullable=False, comment='Айди встречи к которой подключен пользователь'),
    sa.ForeignKeyConstraint(['meet_id'], ['meets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meet_users')
    op.drop_table('meets')
    op.drop_table('users')
    # ### end Alembic commands ###
