"""Add banned_words to rooms

Revision ID: 57061b4eb555
Revises: 
Create Date: 2025-10-26 03:41:43.920654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57061b4eb555'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=1000), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Имя комнаты'),
    sa.Column('code', sa.String(length=255), nullable=False, comment='Уникальный код комнаты'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Айди пользователя кто создал комнату'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Является ли комната активной'),
    sa.Column('schedule', sa.TIMESTAMP(timezone=True), nullable=True, comment='На какую дату запланирована встреча в комнате'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда комната была создана'),
    sa.Column('banned_words', sa.Text(), nullable=False, comment='JSON список запрещенных слов для фильтрации'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_nickname', sa.String(length=255), nullable=False, comment='Имя пользователя'),
    sa.Column('room_id', sa.Integer(), nullable=False, comment='Айди комнаты'),
    sa.Column('text', sa.String(length=115), nullable=False, comment='Текст сообщения'),
    sa.Column('original_text', sa.String(length=115), nullable=False, comment='Оригинальный текст (до фильтрации)'),
    sa.Column('message_type', sa.String(length=50), nullable=False, comment='Тип сообщения: text, system, notification'),
    sa.Column('is_filtered', sa.Boolean(), nullable=False, comment='Было ли сообщение отфильтровано'),
    sa.Column('filtered_reason', sa.String(length=500), nullable=True, comment='Причина фильтрации'),
    sa.Column('send_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Время отправки сообщения'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_nickname', sa.String(length=255), nullable=False, comment='Имя пользователя'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='Уникальный токен пользователя'),
    sa.Column('room_id', sa.Integer(), nullable=False, comment='Айди комнаты к которой подключен пользователь'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_users')
    op.drop_table('room_messages')
    op.drop_table('rooms')
    op.drop_table('users')
    # ### end Alembic commands ###
