"""Add banned_words to rooms

Revision ID: eaeaec86f99d
Revises: fe100062b099
Create Date: 2025-10-25 15:38:40.598254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaeaec86f99d'
down_revision: Union[str, Sequence[str], None] = 'fe100062b099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_nickname', sa.String(length=255), nullable=False, comment='Имя пользователя'),
    sa.Column('room_id', sa.Integer(), nullable=False, comment='Айди комнаты'),
    sa.Column('text', sa.Text(), nullable=False, comment='Текст сообщения'),
    sa.Column('original_text', sa.Text(), nullable=False, comment='Оригинальный текст (до фильтрации)'),
    sa.Column('message_type', sa.String(length=50), nullable=False, comment='Тип сообщения: text, system, notification'),
    sa.Column('is_filtered', sa.Boolean(), nullable=False, comment='Было ли сообщение отфильтровано'),
    sa.Column('filtered_reason', sa.String(length=500), nullable=True, comment='Причина фильтрации'),
    sa.Column('send_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Время отправки сообщения'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rooms', sa.Column('banned_words', sa.Text(), nullable=False, comment='JSON список запрещенных слов для фильтрации'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'banned_words')
    op.drop_table('room_messages')
    # ### end Alembic commands ###
