"""init tables

Revision ID: fe100062b099
Revises: 
Create Date: 2025-10-25 02:08:31.646148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe100062b099'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False, comment='Уникальный код комнаты'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Айди пользователя кто создал комнату'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Является ли комната активной'),
    sa.Column('schedule', sa.TIMESTAMP(timezone=True), nullable=True, comment='На какую дату запланирована встреча в комнате'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда комната была создана'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_nickname', sa.String(length=255), nullable=False, comment='Имя пользователя'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='Уникальный токен пользователя'),
    sa.Column('room_id', sa.Integer(), nullable=False, comment='Айди комнаты к которой подключен пользователь'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_users')
    op.drop_table('rooms')
    op.drop_table('users')
    # ### end Alembic commands ###
